services:
  - type: web
    name: Locally-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URI
        fromSecret: true
      - key: SECRET_KEY
        generateValue: true

  - type: web
    name: Locally-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://shopping-app-backend.onrender.com/api